-- Supabase Database Migration Script for Mentora
-- Includes tables for: profiles, courses, and enrollments
-- Sets up Row Level Security (RLS) and automatic profile creation via auth triggers.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ──────────────────────────────────────────────────────────────────────────────
-- 1. PROFILES TABLE
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    username TEXT UNIQUE,
    full_name TEXT,
    avatar_url TEXT,
    email TEXT,
    role TEXT DEFAULT 'junior_employee' CHECK (role IN ('shop_floor_worker', 'junior_employee', 'senior_employee', 'officer_manager', 'retired_employee', 'admin')),
    employee_id TEXT,
    department TEXT,
    plant TEXT,
    designation TEXT,
    years_of_experience INTEGER DEFAULT 0,
    expertise TEXT[] DEFAULT '{}'::TEXT[],
    skill_level TEXT DEFAULT 'Level 1',
    xp INTEGER DEFAULT 0,
    knowledge_credits INTEGER DEFAULT 0,
    mentora_credits INTEGER DEFAULT 0,
    current_streak INTEGER DEFAULT 0,
    longest_streak INTEGER DEFAULT 0,
    leaderboard_rank INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Users can update their own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- Profile Trigger: Automatically create a profile when a new user signs up in auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, username, full_name, avatar_url, email, role)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
        COALESCE(new.raw_user_meta_data->>'full_name', 'Student'),
        COALESCE(new.raw_user_meta_data->>'avatar_url', 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=60&h=60&fit=crop&auto=format'),
        new.email,
        LOWER(COALESCE(new.raw_user_meta_data->>'role', 'junior_employee'))
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ──────────────────────────────────────────────────────────────────────────────
-- 2. COURSES TABLE
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    instructor TEXT,
    instructor_avatar TEXT,
    thumbnail TEXT,
    category TEXT,
    difficulty TEXT CHECK (difficulty IN ('Beginner', 'Intermediate', 'Advanced')),
    duration TEXT,
    lessons INTEGER DEFAULT 0,
    students INTEGER DEFAULT 0,
    rating NUMERIC(3, 2) DEFAULT 0.0 CHECK (rating >= 0.0 AND rating <= 5.0),
    description TEXT,
    tags TEXT[] DEFAULT '{}',
    modules JSONB DEFAULT '[]'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security for courses
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

-- Courses Policies
CREATE POLICY "Courses are viewable by everyone" ON public.courses
    FOR SELECT USING (true);

CREATE POLICY "Only admins and instructors can insert courses" ON public.courses
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role IN ('instructor', 'admin')
        )
    );

CREATE POLICY "Only admins and instructors can update courses" ON public.courses
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role IN ('instructor', 'admin')
        )
    );

CREATE POLICY "Only admins can delete courses" ON public.courses
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
    );

-- ──────────────────────────────────────────────────────────────────────────────
-- 3. ENROLLMENTS TABLE
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.enrollments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    completed_lessons JSONB DEFAULT '[]'::JSONB, -- Array of lesson IDs completed
    enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_user_course UNIQUE (user_id, course_id)
);

-- Enable Row Level Security for enrollments
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

-- Enrollments Policies
CREATE POLICY "Users can view their own enrollments" ON public.enrollments
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can enroll themselves in courses" ON public.enrollments
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own progress" ON public.enrollments
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can cancel their own enrollments" ON public.enrollments
    FOR DELETE USING (auth.uid() = user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- USER ACTIVITY & BITE PROGRESS TABLES
-- ──────────────────────────────────────────────────────────────────────────────

-- User Activity Progress Table
CREATE TABLE IF NOT EXISTS public.user_activity_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    activity_id BIGINT NOT NULL,
    status TEXT DEFAULT 'available' CHECK (status IN ('locked', 'available', 'in_progress', 'completed')),
    xp_earned INTEGER DEFAULT 0,
    attempts INTEGER DEFAULT 0,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    last_accessed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_user_activity UNIQUE (user_id, activity_id)
);

-- Enable Row Level Security
ALTER TABLE public.user_activity_progress ENABLE ROW LEVEL SECURITY;

-- Activity Progress Policies
CREATE POLICY "Users can view their own activity progress" ON public.user_activity_progress
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own activity progress" ON public.user_activity_progress
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own activity progress" ON public.user_activity_progress
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own activity progress" ON public.user_activity_progress
    FOR DELETE USING (auth.uid() = user_id);

-- User Bite Progress Table
CREATE TABLE IF NOT EXISTS public.user_bite_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    bite_id BIGINT NOT NULL,
    activity_id BIGINT NOT NULL,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    status TEXT DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'completed')),
    attempts INTEGER DEFAULT 0,
    is_correct BOOLEAN DEFAULT false,
    xp_earned INTEGER DEFAULT 0,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    last_accessed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_user_bite UNIQUE (user_id, bite_id)
);

-- Enable Row Level Security
ALTER TABLE public.user_bite_progress ENABLE ROW LEVEL SECURITY;

-- Bite Progress Policies
CREATE POLICY "Users can view their own bite progress" ON public.user_bite_progress
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own bite progress" ON public.user_bite_progress
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own bite progress" ON public.user_bite_progress
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own bite progress" ON public.user_bite_progress
    FOR DELETE USING (auth.uid() = user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- CURRICULUM & PATHS TABLES (Phase 2)
-- ──────────────────────────────────────────────────────────────────────────────

-- Journey Stages Table
CREATE TABLE IF NOT EXISTS public.journey_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    stage_level TEXT,
    order_index INTEGER DEFAULT 0,
    xp_required INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for journey_stages
ALTER TABLE public.journey_stages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Journey stages are viewable by everyone" ON public.journey_stages
    FOR SELECT USING (true);

CREATE POLICY "Only admins and instructors can manage journey stages" ON public.journey_stages
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role IN ('instructor', 'admin')
        )
    );

-- Learning Activities Table
CREATE TABLE IF NOT EXISTS public.learning_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_id BIGINT REFERENCES public.journey_stages(id) ON DELETE CASCADE NOT NULL,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    activity_type TEXT CHECK (activity_type IN ('concept', 'interactive', 'kai_chat', 'challenge', 'scenario', 'quiz', 'reflection', 'mini_project', 'skill_unlock')),
    content JSONB DEFAULT '{}'::JSONB,
    order_index INTEGER DEFAULT 0,
    xp_reward INTEGER DEFAULT 0,
    estimated_minutes INTEGER DEFAULT 0,
    is_required BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for learning_activities
ALTER TABLE public.learning_activities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Learning activities are viewable by everyone" ON public.learning_activities
    FOR SELECT USING (true);

CREATE POLICY "Only admins and instructors can manage learning activities" ON public.learning_activities
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role IN ('instructor', 'admin')
        )
    );

-- Learning Bites Table
CREATE TABLE IF NOT EXISTS public.learning_bites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT REFERENCES public.learning_activities(id) ON DELETE CASCADE NOT NULL,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    stage_id BIGINT REFERENCES public.journey_stages(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    subtitle TEXT,
    bite_type TEXT,
    content JSONB DEFAULT '{}'::JSONB,
    order_index INTEGER DEFAULT 0,
    estimated_minutes INTEGER DEFAULT 0,
    xp_reward INTEGER DEFAULT 0,
    is_required BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for learning_bites
ALTER TABLE public.learning_bites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Learning bites are viewable by everyone" ON public.learning_bites
    FOR SELECT USING (true);

CREATE POLICY "Only admins and instructors can manage learning bites" ON public.learning_bites
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role IN ('instructor', 'admin')
        )
    );

-- Seed Phase 2 Curriculum Data
INSERT INTO public.journey_stages (id, course_id, title, description, stage_level, order_index, xp_required)
VALUES
(101, 1, 'Deep Learning Foundations', 'Understand Perceptrons, multi-layer networks, and activation functions.', 'Beginner', 1, 0),
(102, 1, 'Optimization & Regularization', 'Learn Backpropagation, Gradient Descent variants, and Dropout.', 'Intermediate', 2, 100),
(103, 1, 'Convolutional Networks (CNN)', 'Deep dive into spatial data, convolution operations, and pooling.', 'Advanced', 3, 250)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.learning_activities (id, stage_id, course_id, title, description, activity_type, content, order_index, xp_reward, estimated_minutes, is_required)
VALUES
(111, 101, 1, 'What is a Perceptron?', 'The building block of deep neural networks.', 'concept', '{}'::JSONB, 1, 50, 10, true),
(112, 101, 1, 'Activation Functions Challenge', 'Determine which activation function is right for each layer.', 'quiz', '{}'::JSONB, 2, 50, 15, true),
(113, 102, 1, 'Backpropagation Walkthrough', 'Nesting sub-routines and chain rule computation.', 'scenario', '{}'::JSONB, 3, 50, 20, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.learning_bites (id, activity_id, course_id, stage_id, title, subtitle, bite_type, content, order_index, estimated_minutes, xp_reward, is_required)
VALUES
(1111, 111, 1, 101, 'The Perceptron Model', 'Deep learning starts here', 'concept', '{
  "concept": {
    "title": "The Perceptron Model",
    "description": "A perceptron is a single artificial neuron that takes multiple inputs, multiplies them by weights, sums them, and passes the result through an activation function to generate a binary output."
  },
  "simpleExplanation": {
    "text": "Think of a perceptron like a decision maker that takes inputs, decides how important each input is (weights), sums them, and if they exceed a threshold, triggers an output."
  },
  "visual": {
    "type": "flow",
    "data": {
      "steps": ["Inputs (X1, X2)", "Weights (W1, W2)", "Summation (Σ)", "Activation Function", "Output (Y)"]
    }
  },
  "realWorldExample": {
    "title": "Deciding to go to a concert",
    "description": "Inputs: 1) Is weather good? (Weight = 3). 2) Is ticket cheap? (Weight = 2). Sum threshold = 4. If weather is good, sum = 3 (fails). If both are true, sum = 5 (passes!)."
  },
  "quickActivity": {
    "type": "multiple_choice",
    "question": "What is the role of weights in a perceptron?",
    "options": ["To reset bias to zero", "To represent the importance of each input channel", "To speed up calculation", "To double the output value"],
    "correctAnswer": 1
  },
  "kaiFeedback": {
    "correct": "Correct! Weights determine the scaling importance of each feature input relative to others.",
    "incorrect": "Not quite. Remember that weights scale inputs to signify how important each factor is in decision making."
  }
}'::JSONB, 1, 5, 20, true),
(1112, 111, 1, 101, 'Perceptron Limits & XOR', 'Understanding simple boundaries', 'concept', '{
  "concept": {
    "title": "Perceptron Limits & XOR",
    "description": "Perceptrons can only solve linearly separable problems. They cannot solve functions like XOR because you cannot draw a single straight line to split the positive and negative outputs."
  },
  "simpleExplanation": {
    "text": "A single neuron can draw a straight line to separate data. If the data is mixed in a way that requires a curve or multiple lines (like XOR), a single perceptron fails, requiring multi-layer networks."
  },
  "visual": {
    "type": "comparison",
    "data": {
      "leftTitle": "AND/OR (Linearly Separable)",
      "rightTitle": "XOR (Non-Linearly Separable)",
      "comparisonItems": [
        {"label": "Line boundary", "left": "Draws a single straight line easily", "right": "Requires complex curves or multiple lines"},
        {"label": "Solution", "left": "Solved by single perceptron", "right": "Requires at least 2 layers of networks"}
      ]
    }
  },
  "realWorldExample": {
    "title": "XOR problem visualization",
    "description": "Try separating red dots at (0,1) and (1,0) from green dots at (0,0) and (1,1) with a single straight pencil line. You will find it is geometrically impossible!"
  },
  "quickActivity": {
    "type": "true_false",
    "question": "A single perceptron can easily learn the XOR logic gate functionality.",
    "options": ["True", "False"],
    "correctAnswer": 1
  },
  "kaiFeedback": {
    "correct": "Correct! Single perceptrons cannot solve XOR. This limit led to the development of multi-layer networks.",
    "incorrect": "Try again. Remember that XOR outputs are diagonal and cannot be separated by a single straight line."
  }
}'::JSONB, 2, 5, 20, true)
ON CONFLICT (id) DO NOTHING;

-- ──────────────────────────────────────────────────────────────────────────────
-- MISSIONS & COLLABORATIVE TABLES (Phase 3)
-- ──────────────────────────────────────────────────────────────────────────────

-- Missions Table
CREATE TABLE IF NOT EXISTS public.missions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT,
    assigned_role TEXT,
    reward_type TEXT CHECK (reward_type IN ('xp', 'credits', 'both')),
    reward_amount INTEGER DEFAULT 0,
    estimated_time TEXT,
    due_date TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for missions
ALTER TABLE public.missions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Missions are viewable by everyone" ON public.missions
    FOR SELECT USING (true);

-- User Missions Progress Table
CREATE TABLE IF NOT EXISTS public.user_missions_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    mission_id BIGINT REFERENCES public.missions(id) ON DELETE CASCADE NOT NULL,
    status TEXT DEFAULT 'assigned' CHECK (status IN ('assigned', 'in_progress', 'completed', 'failed')),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_user_mission UNIQUE (user_id, mission_id)
);

-- Enable RLS for user_missions_progress
ALTER TABLE public.user_missions_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own missions progress" ON public.user_missions_progress
    FOR ALL USING (auth.uid() = user_id);

-- Questions Table (Q&A Board)
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    author_name TEXT NOT NULL,
    department TEXT,
    topic TEXT,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for questions
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Questions are viewable by everyone" ON public.questions
    FOR SELECT USING (true);

CREATE POLICY "Users can ask questions" ON public.questions
    FOR INSERT WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Users can update their own questions" ON public.questions
    FOR UPDATE USING (auth.uid() = author_id);

-- Answers Table
CREATE TABLE IF NOT EXISTS public.answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE NOT NULL,
    author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    author_name TEXT NOT NULL,
    author_role TEXT,
    content TEXT NOT NULL,
    answer_type TEXT DEFAULT 'standard' CHECK (answer_type IN ('standard', 'expert', 'verified')),
    verified BOOLEAN DEFAULT false,
    helpful_count INTEGER DEFAULT 0,
    source TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for answers
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Answers are viewable by everyone" ON public.answers
    FOR SELECT USING (true);

CREATE POLICY "Users can insert answers" ON public.answers
    FOR INSERT WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Users can update their own answers" ON public.answers
    FOR UPDATE USING (auth.uid() = author_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- KNOWLEDGE BASE & SAVED ITEMS TABLES (Phase 4)
-- ──────────────────────────────────────────────────────────────────────────────

-- Knowledge Articles (SOPs) Table
CREATE TABLE IF NOT EXISTS public.knowledge_articles (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    department TEXT,
    views INTEGER DEFAULT 0,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    is_preserved BOOLEAN DEFAULT false,
    is_official BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for knowledge_articles
ALTER TABLE public.knowledge_articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Knowledge articles are viewable by everyone" ON public.knowledge_articles
    FOR SELECT USING (true);

-- Saved Items (Bookmarks) Table
CREATE TABLE IF NOT EXISTS public.saved_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    item_id TEXT NOT NULL,
    item_type TEXT CHECK (item_type IN ('course', 'sop', 'question', 'recording', 'ai_usecase')),
    title TEXT NOT NULL,
    desc_content TEXT,
    category TEXT,
    page_route TEXT,
    saved_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_user_item UNIQUE (user_id, item_id, item_type)
);

-- Enable RLS for saved_items
ALTER TABLE public.saved_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own saved items" ON public.saved_items
    FOR ALL USING (auth.uid() = user_id);

-- Skills Table (Skills Catalog)
CREATE TABLE IF NOT EXISTS public.skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    proficiency TEXT CHECK (proficiency IN ('Beginner', 'Intermediate', 'Advanced', 'Expert')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for skills
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Skills catalog is viewable by everyone" ON public.skills
    FOR SELECT USING (true);

-- User Skills Progress Table
CREATE TABLE IF NOT EXISTS public.user_skills_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    skill_id BIGINT REFERENCES public.skills(id) ON DELETE CASCADE NOT NULL,
    progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_user_skill UNIQUE (user_id, skill_id)
);

-- Enable RLS for user_skills_progress
ALTER TABLE public.user_skills_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own skills progress" ON public.user_skills_progress
    FOR ALL USING (auth.uid() = user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- REWARDS STORE TABLES (Phase 5)
-- ──────────────────────────────────────────────────────────────────────────────

-- Rewards Catalog Table
CREATE TABLE IF NOT EXISTS public.rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    cost INTEGER DEFAULT 0,
    category TEXT,
    availability BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for rewards
ALTER TABLE public.rewards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Rewards are viewable by everyone" ON public.rewards
    FOR SELECT USING (true);

-- Reward Redemptions (Transactions) Table
CREATE TABLE IF NOT EXISTS public.reward_redemptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    reward_id BIGINT REFERENCES public.rewards(id) ON DELETE CASCADE NOT NULL,
    cost_paid INTEGER NOT NULL,
    redeemed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for reward_redemptions
ALTER TABLE public.reward_redemptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own redemptions" ON public.reward_redemptions
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can redeem rewards" ON public.reward_redemptions
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- SEED DATA FOR NEW TABLES
-- ──────────────────────────────────────────────────────────────────────────────

-- Seed Missions
INSERT INTO public.missions (id, title, description, type, assigned_role, reward_type, reward_amount, estimated_time, due_date)
VALUES
(101, 'Daily Safety Drill Quiz', 'Complete the 5-question quick quiz on Boiler Room safety regulations.', 'QUIZ', 'SHOP_FLOOR_WORKER', 'xp', 150, '5 mins', 'Today, 11:59 PM'),
(102, 'Identify 1 Machine Anomaly', 'Check the HVAC unit status panel, log operational readings.', 'SOP_READING', 'SHOP_FLOOR_WORKER', 'both', 200, '15 mins', 'Tomorrow, 5:00 PM'),
(103, 'Complete TypeScript Refactoring Module', 'Finish the hands-on coding challenges for Advanced Types.', 'LEARNING', 'JUNIOR_EMPLOYEE', 'both', 250, '45 mins', 'Today, 11:59 PM'),
(104, 'Help 1 Peer on Knowledge Exchange', 'Answer any open question tagged with Node.js, SQL, or React.', 'KNOWLEDGE_SHARING', 'JUNIOR_EMPLOYEE', 'credits', 50, '15 mins', 'Completed today'),
(105, 'Conduct Q&A Review Session', 'Verify and review answers submitted by Junior staff.', 'MENTORING', 'SENIOR_EMPLOYEE', 'both', 300, '30 mins', 'In 2 days'),
(106, 'Create Weekly Safety Policy Article', 'Draft and publish a brief 300-word advisory article.', 'EXPERIENCE_SHARING', 'SENIOR_EMPLOYEE', 'credits', 100, '60 mins', 'This Friday')
ON CONFLICT (id) DO NOTHING;

-- Seed Skills
INSERT INTO public.skills (id, name, category, proficiency)
VALUES
(201, 'Machine Operations', 'Operations', 'Advanced'),
(202, 'Safety Compliance', 'Operations', 'Expert'),
(203, 'Hydraulic Systems', 'Mechanical', 'Intermediate'),
(204, 'React Development', 'Software', 'Intermediate'),
(205, 'TypeScript & ES6+', 'Software', 'Intermediate'),
(206, 'PLCs & Automation', 'Robotics', 'Expert'),
(207, 'Industrial IoT', 'Hardware', 'Advanced')
ON CONFLICT (id) DO NOTHING;

-- Seed Knowledge base guidelines
INSERT INTO public.knowledge_articles (id, title, department, views, author, content, is_preserved, is_official)
VALUES
('sop_14', 'Standard Boiler Valve Override Procedure', 'Maintenance', 320, 'Devendra Prasad', 'Manual mechanical lock overrides: isolation of breaker panel 4B is required before using the override lever beneath the pressure gauge.', true, true),
('sop_104', 'Modbus Gateway Telemetry Configuration Guidelines', 'R&D / IT', 180, 'Arjun Mehta', 'Standard configuration steps for mapping Modbus registers into the SCADA console over RS-485 interfaces.', true, true),
('sop_202', 'Safe Lockout/Tagout (LOTO) Protocols 2026', 'Safety & EHS', 540, 'Sarah Chen', 'Centralized safety regulations detailing key-lock placements and color-coded tag indicators.', false, true),
('sop_9', 'Turbine Thermal Expansion & Shaft Vibration Safety Limits', 'Engineering', 210, 'Devendra Prasad', 'A guidelines memo outlining maximum operational vibration limits and temperature cooldown periods.', false, true)
ON CONFLICT (id) DO NOTHING;

-- Seed Rewards Catalog
INSERT INTO public.rewards (id, title, description, cost, category, availability)
VALUES
(701, 'Tata Steel Premium Tech Hoodie', 'Heavyweight organic cotton hoodie with custom Tata Steel Pune insignia.', 500, 'Merchandise', true),
(702, 'Tata Steel Travel Mug', 'Vacuum insulated thermal travel mug keeping steam utilities hot.', 150, 'Merchandise', true),
(703, 'Advanced IIoT Robotics Course Voucher', 'Enrolls you in specialized PLC automation labs in Bengaluru.', 200, 'Courses', true),
(704, 'Private Webinar Q&A with Executive Panel', 'Attend a live virtual executive session on steel manufacturing tech.', 300, 'Webinars', true)
ON CONFLICT (id) DO NOTHING;

-- ──────────────────────────────────────────────────────────────────────────────
-- 4. UTILS & HELPERS
-- ──────────────────────────────────────────────────────────────────────────────

-- Trigger to automatically update updated_at fields
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER update_courses_modtime
    BEFORE UPDATE ON public.courses
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

CREATE OR REPLACE TRIGGER update_enrollments_modtime
    BEFORE UPDATE ON public.enrollments
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- 5. SEED MOCK DATA (Optional - can be run to initialize DB state)
-- ──────────────────────────────────────────────────────────────────────────────
INSERT INTO public.courses (id, title, instructor, instructor_avatar, thumbnail, category, difficulty, duration, lessons, students, rating, description, tags, modules)
VALUES
(
    1,
    'Advanced Machine Learning & Neural Networks',
    'Dr. Sarah Chen',
    'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=340&fit=crop&auto=format',
    'AI & ML',
    'Advanced',
    '42h 30m',
    64,
    4280,
    4.9,
    'Master the fundamentals of machine learning, deep learning, and neural network architectures used in production AI systems at scale.',
    ARRAY['Python', 'TensorFlow', 'PyTorch', 'Deep Learning'],
    '[
        {
            "id": 1, "title": "Introduction to Neural Networks",
            "lessons": [
                { "id": 1, "title": "What is a Neural Network?", "duration": "12:30" },
                { "id": 2, "title": "Perceptrons and Activation Functions", "duration": "18:45" },
                { "id": 3, "title": "Forward Propagation Explained", "duration": "22:10" }
            ]
        },
        {
            "id": 2, "title": "Deep Learning Fundamentals",
            "lessons": [
                { "id": 4, "title": "Backpropagation Algorithm", "duration": "28:00" },
                { "id": 5, "title": "Gradient Descent Variants", "duration": "24:15" },
                { "id": 6, "title": "Regularization Techniques", "duration": "20:30" }
            ]
        },
        {
            "id": 3, "title": "Convolutional Neural Networks",
            "lessons": [
                { "id": 7, "title": "Convolution Operations", "duration": "31:20" },
                { "id": 8, "title": "Pooling and Stride", "duration": "15:45" },
                { "id": 9, "title": "CNN Architectures: ResNet, VGG", "duration": "42:00" }
            ]
        },
        {
            "id": 4, "title": "Transformers & Attention Mechanisms",
            "lessons": [
                { "id": 10, "title": "Attention Mechanism Explained", "duration": "35:00" },
                { "id": 11, "title": "Transformer Architecture Deep Dive", "duration": "48:30" },
                { "id": 12, "title": "Fine-tuning Pre-trained Models", "duration": "38:15" }
            ]
        }
    ]'::JSONB
),
(
    2,
    'Cybersecurity & Zero Trust Architecture',
    'Marcus Rivera',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&h=340&fit=crop&auto=format',
    'Security',
    'Intermediate',
    '28h 15m',
    48,
    3150,
    4.8,
    'Build enterprise security frameworks using zero-trust principles, threat modeling, and advanced penetration testing methodologies.',
    ARRAY['Security', 'Zero Trust', 'Compliance', 'Networking'],
    '[]'::JSONB
),
(
    3,
    'Executive Leadership & Strategic Thinking',
    'Amanda Foster',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=340&fit=crop&auto=format',
    'Leadership',
    'Intermediate',
    '18h 45m',
    32,
    5620,
    4.7,
    'Develop executive presence, strategic thinking frameworks, and high-performance team management skills for modern enterprise.',
    ARRAY['Leadership', 'Strategy', 'Management', 'Communication'],
    '[]'::JSONB
),
(
    4,
    'Data Analytics & Business Intelligence',
    'James Okafor',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=340&fit=crop&auto=format',
    'Data Science',
    'Beginner',
    '24h 20m',
    40,
    6890,
    4.8,
    'Transform raw data into actionable business insights using SQL, Python, Power BI, and advanced statistical analysis techniques.',
    ARRAY['SQL', 'Python', 'Power BI', 'Statistics'],
    '[]'::JSONB
),
(
    5,
    'Cloud Architecture & DevOps Engineering',
    'Priya Sharma',
    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=340&fit=crop&auto=format',
    'Cloud & DevOps',
    'Advanced',
    '36h 10m',
    58,
    2740,
    4.9,
    'Design scalable cloud infrastructure on AWS, Azure, and GCP with modern DevOps practices, Kubernetes, and CI/CD pipelines.',
    ARRAY['AWS', 'Kubernetes', 'Terraform', 'Docker'],
    '[]'::JSONB
),
(
    6,
    'Product Management & Agile Methodology',
    'Daniel Kim',
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=340&fit=crop&auto=format',
    'Product',
    'Intermediate',
    '22h 00m',
    36,
    4120,
    4.6,
    'Learn product discovery, roadmapping, stakeholder management, and agile frameworks used at top tech companies worldwide.',
    ARRAY['Agile', 'Scrum', 'Roadmapping', 'OKRs'],
    '[]'::JSONB
)
ON CONFLICT (id) DO NOTHING;
