-- Supabase Database Migration Script for Mentora
-- Includes tables for: profiles, courses, and enrollments
-- Sets up Row Level Security (RLS) and automatic profile creation via auth triggers.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ──────────────────────────────────────────────────────────────────────────────
-- 1. PROFILES TABLE
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    username TEXT UNIQUE,
    full_name TEXT,
    avatar_url TEXT,
    email TEXT,
    role TEXT DEFAULT 'student' CHECK (role IN ('student', 'instructor', 'admin')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Users can update their own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- Profile Trigger: Automatically create a profile when a new user signs up in auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, username, full_name, avatar_url, email, role)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
        COALESCE(new.raw_user_meta_data->>'full_name', 'Student'),
        COALESCE(new.raw_user_meta_data->>'avatar_url', 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=60&h=60&fit=crop&auto=format'),
        new.email,
        COALESCE(new.raw_user_meta_data->>'role', 'student')
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ──────────────────────────────────────────────────────────────────────────────
-- 2. COURSES TABLE
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    instructor TEXT,
    instructor_avatar TEXT,
    thumbnail TEXT,
    category TEXT,
    difficulty TEXT CHECK (difficulty IN ('Beginner', 'Intermediate', 'Advanced')),
    duration TEXT,
    lessons INTEGER DEFAULT 0,
    students INTEGER DEFAULT 0,
    rating NUMERIC(3, 2) DEFAULT 0.0 CHECK (rating >= 0.0 AND rating <= 5.0),
    description TEXT,
    tags TEXT[] DEFAULT '{}',
    modules JSONB DEFAULT '[]'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security for courses
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

-- Courses Policies
CREATE POLICY "Courses are viewable by everyone" ON public.courses
    FOR SELECT USING (true);

CREATE POLICY "Only admins and instructors can insert courses" ON public.courses
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role IN ('instructor', 'admin')
        )
    );

CREATE POLICY "Only admins and instructors can update courses" ON public.courses
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role IN ('instructor', 'admin')
        )
    );

CREATE POLICY "Only admins can delete courses" ON public.courses
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
    );

-- ──────────────────────────────────────────────────────────────────────────────
-- 3. ENROLLMENTS TABLE
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.enrollments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    completed_lessons JSONB DEFAULT '[]'::JSONB, -- Array of lesson IDs completed
    enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_user_course UNIQUE (user_id, course_id)
);

-- Enable Row Level Security for enrollments
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

-- Enrollments Policies
CREATE POLICY "Users can view their own enrollments" ON public.enrollments
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can enroll themselves in courses" ON public.enrollments
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own progress" ON public.enrollments
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can cancel their own enrollments" ON public.enrollments
    FOR DELETE USING (auth.uid() = user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 4. UTILS & HELPERS
-- ──────────────────────────────────────────────────────────────────────────────

-- Trigger to automatically update updated_at fields
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER update_courses_modtime
    BEFORE UPDATE ON public.courses
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

CREATE OR REPLACE TRIGGER update_enrollments_modtime
    BEFORE UPDATE ON public.enrollments
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- ──────────────────────────────────────────────────────────────────────────────
-- 5. SEED MOCK DATA (Optional - can be run to initialize DB state)
-- ──────────────────────────────────────────────────────────────────────────────
INSERT INTO public.courses (id, title, instructor, instructor_avatar, thumbnail, category, difficulty, duration, lessons, students, rating, description, tags, modules)
VALUES
(
    1,
    'Advanced Machine Learning & Neural Networks',
    'Dr. Sarah Chen',
    'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=340&fit=crop&auto=format',
    'AI & ML',
    'Advanced',
    '42h 30m',
    64,
    4280,
    4.9,
    'Master the fundamentals of machine learning, deep learning, and neural network architectures used in production AI systems at scale.',
    ARRAY['Python', 'TensorFlow', 'PyTorch', 'Deep Learning'],
    '[
        {
            "id": 1, "title": "Introduction to Neural Networks",
            "lessons": [
                { "id": 1, "title": "What is a Neural Network?", "duration": "12:30" },
                { "id": 2, "title": "Perceptrons and Activation Functions", "duration": "18:45" },
                { "id": 3, "title": "Forward Propagation Explained", "duration": "22:10" }
            ]
        },
        {
            "id": 2, "title": "Deep Learning Fundamentals",
            "lessons": [
                { "id": 4, "title": "Backpropagation Algorithm", "duration": "28:00" },
                { "id": 5, "title": "Gradient Descent Variants", "duration": "24:15" },
                { "id": 6, "title": "Regularization Techniques", "duration": "20:30" }
            ]
        },
        {
            "id": 3, "title": "Convolutional Neural Networks",
            "lessons": [
                { "id": 7, "title": "Convolution Operations", "duration": "31:20" },
                { "id": 8, "title": "Pooling and Stride", "duration": "15:45" },
                { "id": 9, "title": "CNN Architectures: ResNet, VGG", "duration": "42:00" }
            ]
        },
        {
            "id": 4, "title": "Transformers & Attention Mechanisms",
            "lessons": [
                { "id": 10, "title": "Attention Mechanism Explained", "duration": "35:00" },
                { "id": 11, "title": "Transformer Architecture Deep Dive", "duration": "48:30" },
                { "id": 12, "title": "Fine-tuning Pre-trained Models", "duration": "38:15" }
            ]
        }
    ]'::JSONB
),
(
    2,
    'Cybersecurity & Zero Trust Architecture',
    'Marcus Rivera',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&h=340&fit=crop&auto=format',
    'Security',
    'Intermediate',
    '28h 15m',
    48,
    3150,
    4.8,
    'Build enterprise security frameworks using zero-trust principles, threat modeling, and advanced penetration testing methodologies.',
    ARRAY['Security', 'Zero Trust', 'Compliance', 'Networking'],
    '[]'::JSONB
),
(
    3,
    'Executive Leadership & Strategic Thinking',
    'Amanda Foster',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=340&fit=crop&auto=format',
    'Leadership',
    'Intermediate',
    '18h 45m',
    32,
    5620,
    4.7,
    'Develop executive presence, strategic thinking frameworks, and high-performance team management skills for modern enterprise.',
    ARRAY['Leadership', 'Strategy', 'Management', 'Communication'],
    '[]'::JSONB
),
(
    4,
    'Data Analytics & Business Intelligence',
    'James Okafor',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=340&fit=crop&auto=format',
    'Data Science',
    'Beginner',
    '24h 20m',
    40,
    6890,
    4.8,
    'Transform raw data into actionable business insights using SQL, Python, Power BI, and advanced statistical analysis techniques.',
    ARRAY['SQL', 'Python', 'Power BI', 'Statistics'],
    '[]'::JSONB
),
(
    5,
    'Cloud Architecture & DevOps Engineering',
    'Priya Sharma',
    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=340&fit=crop&auto=format',
    'Cloud & DevOps',
    'Advanced',
    '36h 10m',
    58,
    2740,
    4.9,
    'Design scalable cloud infrastructure on AWS, Azure, and GCP with modern DevOps practices, Kubernetes, and CI/CD pipelines.',
    ARRAY['AWS', 'Kubernetes', 'Terraform', 'Docker'],
    '[]'::JSONB
),
(
    6,
    'Product Management & Agile Methodology',
    'Daniel Kim',
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&h=60&fit=crop&auto=format',
    'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=340&fit=crop&auto=format',
    'Product',
    'Intermediate',
    '22h 00m',
    36,
    4120,
    4.6,
    'Learn product discovery, roadmapping, stakeholder management, and agile frameworks used at top tech companies worldwide.',
    ARRAY['Agile', 'Scrum', 'Roadmapping', 'OKRs'],
    '[]'::JSONB
)
ON CONFLICT (id) DO NOTHING;
